linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: false
  presets:
    - bugs
    - complexity
    - format
    - performance
    - style
    - unused
  enable:
    - gci
  disable:
    - asciicheck
    - gofumpt